on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps: 
      - name: Setup Node w/ pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i -g pnpm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Blog
        run: pnpm install && pnpm run build
      # - name: Publish to Cloudflare Pages
      #   uses: "cloudflare/pages-action@1"
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: "wuul-blog"
      #     directory: "dist"
      #     gitHubToken: ${{secrets.GITHUB_TOKEN}}
      