on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps: 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with: 
          version: 8.10.2
          run_install: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Blog
        run: pnpm install && pnpm run build
      - name: Publish to Cloudflare Pages
        uses: "cloudflare/pages-action@1"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "wuul-blog"
          directory: "dist"
          gitHubToken: ${{secrets.GITHUB_TOKEN}}
      